# Generated by Django 5.1.6 on 2026-02-12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('review_link_2gis', models.URLField(blank=True)),
                ('review_link_yandex', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('pickup', 'Pickup'), ('tire_service', 'Tire service'), ('common', 'Common')], max_length=32)),
                ('type', models.CharField(choices=[('rating', 'Rating'), ('yes_no', 'Yes/No'), ('text', 'Text')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={'ordering': ('order', 'id')},
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('order_number', models.CharField(max_length=64)),
                ('service_type', models.CharField(choices=[('pickup', 'Pickup'), ('tire_service', 'Tire service'), ('both', 'Both')], max_length=32)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='survey.point')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('answer_yes_no', models.BooleanField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='survey.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.survey')),
            ],
            options={'unique_together': {('survey', 'question')}},
        ),
    ]
