# Generated by Django 5.1.6 on 2026-02-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='service_type',
        ),
        migrations.AddField(
            model_name='survey',
            name='was_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='was_tire_service',
            field=models.BooleanField(default=False),
        ),
    ]
