# Generated by Django 5.1.6 on 2026-02-12 08:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_survey_service_type_survey_was_pickup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, verbose_name='Текстовый ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_yes_no',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ответ Да/Нет'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='survey.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.survey', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('pickup', 'Получение'), ('tire_service', 'Шиномонтаж'), ('common', 'Общие')], max_length=32, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Обязательный'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('rating', 'Оценка'), ('yes_no', 'Да / Нет'), ('text', 'Текст')], max_length=32, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершен в'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='order_number',
            field=models.CharField(max_length=64, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='survey.point', verbose_name='ПВЗ'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='was_pickup',
            field=models.BooleanField(default=False, verbose_name='Было получение'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='was_tire_service',
            field=models.BooleanField(default=False, verbose_name='Был шиномонтаж'),
        ),
    ]
